version: '3'
 
services:
  db:
    image: mariadb:10.5.8
    container_name: mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: 'root123'
      MYSQL_DATABASE: 'doccare'
      MYSQL_USER: 'nagarjun'
      MYSQL_PASSWORD: 'nags123'
    ports:
      - "3306:3306"
    volumes:
        - mysql_volume:/var/lib/mysql
volumes:
 mysql_volume:

